---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.10.24

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    os_type: windows

suites:
  - name: default
    attributes:
